### ISSUE TITLE
Integrate a Masked Input with formsy-react-components

### ISSUE THREAD

**Issue by carlos-sarmiento** [twisty/formsy-react-components#100]
I'm looking to integrate a separate react component that implements a textbox with masked input. I've been looking through the source code trying to understand how could it be done, but I'm at a loss on how. 

Could you provide any guidance on how this could be done? It would be very useful to extend the project to allow using inputs developed by someone else.

**Comment by twisty** [comment]
Hi @carlos-sarmiento, have you seen [`formsy-react`'s how to use](https://github.com/christianalfoni/formsy-react#how-to-use) advice? These components should work in conjunction with any `formsy-react` complaint component.

If you want to lay-out your component in a similar way to these `formsy-react-components`, have a look at the [row component](https://github.com/twisty/formsy-react-components/blob/release-0.x/src/row.js). Hope that helps?

**Comment by nihlton** [comment]
@carlos-sarmiento 

I make no promises that this is a *good* solutions, but we're accomplishing masked inputs with this module:
https://github.com/nihlton/input-mask

Input component is like:
http://pastebin.com/a3ySBqme

Usage:
```
<Input
  type='text'
  placeholder='Enter Phone Here'
  name='phoneNumber'
  pattern={{inputMask: '(___) ___ - ____', numberMask: '_'}}
  required />
```
