### ISSUE TITLE
React 15.5 deprecations

### ISSUE THREAD

**Issue by erzzo** [twisty/formsy-react-components#103]
https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

- [ ] propTypes
- [ ] createClass

**Comment by twisty** [comment]
Thanks @erzzo. Duly noted. The `createClass` task is done on the master branch. The Proptypes migration doesn't look too painful! Both are on my todo list!

**Comment by erzzo** [comment]
yep, great

**Comment by SachaG** [comment]
Any update on this? Could the current master branch be pushed to NPM?

**Comment by twisty** [comment]
Golly gosh, where has that month and a half gone?

Have fixed `propTypes` in an incoming commit. Have just bumped Jest and just trying to squash a few more deprecation warnings that are coming from goodness-knows-where.

Will make a release to `npm` soon (days not weeks).

**Comment by twisty** [comment]
https://github.com/twisty/formsy-react-components/releases/tag/v1.0.0-alpha.1
