### ISSUE TITLE
Autocomplete dropdown values getting reset in IE11

### ISSUE THREAD

**Issue by sean-ww** [twisty/formsy-react-components#104]
Using the autocomplete dropdown to select a value doesn't work in IE11. Only if I type in the input box, or go directly to submit, will the value be recognised. Otherwise, changing another element after using the autocomplete dropdown will cause the input to reset to its previous value.

![autocompleteissue2](https://cloud.githubusercontent.com/assets/12208691/25671964/bd52d668-3029-11e7-90eb-70f3d7d5c196.gif)

**Comment by twisty** [comment]
Hi, looks like either `onchange` or `onblur` (or both!) aren't firing as a result of the autocomplete.

There are various reasons this might be happening, [this page](https://msdn.microsoft.com/en-us/library/dn629640(v=vs.85).aspx) may help?

**Comment by sean-ww** [comment]
It seems it doesn't fire the `propertychange` event that react listens to in React 15. This is based on [facebook/react#6614](https://github.com/facebook/react/issues/6614)

**Comment by twisty** [comment]
I notice this was recently marked fixed in https://github.com/facebook/react/issues/6614#issuecomment-308207660.

Haven't had chance to check this yet, does this solve the issue for you?

**Comment by sean-ww** [comment]
Yes, I updated to the latest version (v15.6.1) and it works just fine 👍
