### ISSUE TITLE
Handling number values with radio buttons

### ISSUE THREAD

**Issue by SachaG** [twisty/formsy-react-components#105]
I don't know if this is a problem with the way I've set things up or a limitation of FRC, but I can't seem to find a good way to handle number values with radio buttons. 

The problem is that the logic that checks if a radio button is currently checked uses `this.props.value === radio.value`. Which means that if the option value is a number, but the value passed through the props is a string, the check will fail (because `1 !== "1"`).

And it does seem like when you get the value with `event.currentTarget.value`, it's always a string no matter what (after all you can't tell the difference when you write `<input value="1"/>`). 

How should we handle this? Would it be possible to change the Radio component to `this.props.value == radio.value` instead to be more flexible?

**Comment by twisty** [comment]
I see what you mean but I'm hesitant to add loose equality checking. My advice is to use strings, convert the value to a number using `formsy-react`'s [`mapping`](https://github.com/christianalfoni/formsy-react/blob/master/API.md#mapping) mechanism. (by casting to type, or using the value as a lookup key).

**Comment by twisty** [comment]
Just checked master branch (from which future version of this package will be cut) and there is now a [PropType definition requiring the values of radio buttons to be strings](https://github.com/twisty/formsy-react-components/blob/v1.0.0-alpha.1/src/components/radio-group.js#L85-L91).

**Comment by SachaG** [comment]
Thanks, that makes sense. Good to know about `mapping`.
