### ISSUE TITLE
Getting latest (1.0.0-dev) version

### ISSUE THREAD

**Issue by vasyas** [twisty/formsy-react-components#106]
How do I use the latest (1.0.0-dev) version in my project? 
It contains useful fixes for me.

npm i -S twisty/formsy-react-components
is not working.

**Comment by twisty** [comment]
Hi, hopefully you figured out that you can [depend on git branches in npm](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies).

If not, you'll be pleased to hear that the master branch has been released as an alpha on `npm`, see: https://github.com/twisty/formsy-react-components/releases/tag/v1.0.0-alpha.1
