### ISSUE TITLE
change DOM structure in <RadioGroup> ?

### ISSUE THREAD

**Issue by user928** [twisty/formsy-react-components#107]
Hello is it possible to add a `<span>` right after `<input type="radio">` inside `<RadioGroup>` component ?

![add-span](https://cloud.githubusercontent.com/assets/12034888/26789107/8e6d2e84-4a0f-11e7-8be5-6b51f320665b.jpg)

**Comment by twisty** [comment]
Hi, sorry but that's not possible at the moment. Generally, if there isn't an example to follow in the [Bootstrap forms docs](http://getbootstrap.com/css/#forms), it's not implemented in this library.
