### ISSUE TITLE
import issues with v1.0.0-alpha.1

### ISSUE THREAD

**Issue by timothyallan** [twisty/formsy-react-components#108]
Heya!

Just updated to 1.0a1 to stop seeing the createclass warnings in my console, and all my imports aren't working anymore. It looks like there's now just a `default` export so:
```import { Textarea } from 'formsy-react-components';```

no longer works in my Typescript project.
I can however get it to work by doing:

```
import * as ReactComponents from 'formsy-react-components';
const Textarea = ReactComponents.default.Textarea;
```

Is this by design? i.e. Should I go and change everything in my project?

**Comment by twisty** [comment]
Good catch; this isn't by design, and it will be changed...

**Comment by twisty** [comment]
Changed in e43fb3b2dfde354340c0cca713e5fcab536345eb. I'll be making an `alpha-2` release on npm later.

**Comment by twisty** [comment]
[alpha-2](https://github.com/twisty/formsy-react-components/releases/tag/v1.0.0-alpha.2) has been released.
