### ISSUE TITLE
is there a way for get status of validation? true of false? 

### ISSUE THREAD

**Issue by miladbruce** [twisty/formsy-react-components#109]
is there a way for get status of validation? true of false? 
for example on submit when validation true

**Comment by jcalfee** [comment]
Knowing the validation status in the onSubmit would be useful.  The second parameter could be an object to allow for safe API expansaion later:
```js
const EnterPasswordForm = props => {
  const submit = (data, {valid}) => {
    if(valid) {
      props.onSubmit(data)
    }
  }
  return (
    <Form onSubmit={submit}>
       ..
    </Form>
  )
}
```

**Comment by twisty** [comment]
Hi, have you seen the [formsy form methods](https://github.com/christianalfoni/formsy-react/blob/master/API.md#formsyform) like ` onValidSubmit()` or `onInvalidSubmit()`?

**Comment by twisty** [comment]
Closing this one. Presume you sorted it.
