### ISSUE TITLE
Textarea element is always null 1.0a2

### ISSUE THREAD

**Issue by timothyallan** [twisty/formsy-react-components#110]
On 1.0alpha2, I'm finding that the element component of my TextArea is always null.

```
<Textarea
          ref={obj => {
            this.textarea = obj;
          }}
          componentRef={node => {
            this.textareaComponent = node;
          }}
          name={this.props.name}
          disabled={this.props.disabled}
          onChange={this.handleOnChange}
          onBlur={this.handleOnBlur}
          onFocus={this.props.onFocus || undefined}
          placeholder={this.props.placeholder || undefined}
          validations={validations}
          validationErrors={validationErrors}
          value={this.props.value || ''}
          layout="elementOnly"
          style={noRowScrollStyle}
        />
```
Referencing `this.textareaComponent`, I see it's a proper
 object, but the element portion always reports null, even though it's on screen.

<img width="332" alt="screen shot 2017-09-13 at 4 05 59 pm" src="https://user-images.githubusercontent.com/1995135/30403143-88c556aa-989d-11e7-8e92-8824a53f81e9.png">

**Comment by twisty** [comment]
Okay, good catch. Fix incoming. Will make an alpha 3 release within the next day or so.

**Comment by timothyallan** [comment]
Great! My un focused TextAreas await.

**Comment by twisty** [comment]
Fixed in latest releases.

**Comment by timothyallan** [comment]
Thanks! Just got a chance to try the latest version and am now getting `Uncaught TypeError: (0 , _formsyReact.Wrapper) is not a function`... because `.Wrapper` ain't there!

![screen shot 2017-09-17 at 3 41 35 pm](https://user-images.githubusercontent.com/1995135/30525174-2a18d080-9bbf-11e7-83a4-0252cd436cc6.png)


```
"formsy-react": "^0.19.5",
"formsy-react-components": "^1.0.0-alpha.4",
```

**Comment by twisty** [comment]
Try using version `^1.0.0` (or `@beta`) for the `formsy-react` dependency. (I should probably add this as a `peerDependency`).

**Comment by timothyallan** [comment]
Ah, didn't even realize they had a beta going. After much futzing around with the breaking changes to the HOC in 1.0.0 beta, that seems to have fixed the Wrapper error! Thanks for pointing me in the right direction.
