### ISSUE TITLE
Enter submits invalid form

### ISSUE THREAD

**Issue by jcalfee** [twisty/formsy-react-components#112]
I just updated to 1.0.0-alpha.5

I'm able to type a short password in input1 and press enter quickly .. the form will submit even though it did not confirm.
 
```js
<Form onValidSubmit={this.submit}>
            <Input type="password" name="password" id="password"
              label="Passphrase" placeholder="Password"
            />
            <Input
              type="password" name="confirm" label="Confirm" placeholder="Confirm"
              validations="equalsField:password"
              validationErrors={{equalsField: 'Passwords must match.'}}
            />
            <input type="submit" defaultValue="Submit"/>
</Form>
```

**Comment by twisty** [comment]
I'll have to dig a little deeper to get to the bottom of this, but I'll take a guess at what might be happening...

For "texty" types of input we perform a `setValue` call 0.5 seconds after typing stops (`onChange` event + 500ms) . This is designed to stop validations occurring on every keystroke.

In addition, when an input loses focus (`onBlur` event) we cancel pending `setValue` calls, and trigger a new  immediate `setValue` call, which in turn triggers a form validation.

It may be that hitting <kbd>enter</kbd> is triggering a form submission without (or before) calling the `onChange` event. I think maybe the `onChange` event is not firing when hitting the <kbd>return / enter</kbd> key.

https://stackoverflow.com/questions/14771023/change-event-not-fired-on-return-key

This would explain why short delay works, but "quick typing" doesn't.

In the interim, you could try setting the `changeDebounceInterval` to `0` and see if that fixes it.

Tim.

**Comment by twisty** [comment]
Maybe just triggering a `setValue` call for <kbd>enter / return</kbd> would fix this?

**Comment by jcalfee** [comment]
You could create a callback or Promise and resolve it when the timeout finishes.  On the submit make sure the callback is non-exist or if you find the callback register and submit after the callback finishes.

Thanks, I will increase changeDebounceInterval just to have a faster feel to the form, most validations are very quick.  In the long a promise async validation would be important.  The work around I use is to pull the value out of the DOM.  It is only 1 field so that is not so bad in my case.  Data consistency on the other hand is very important.

**Comment by jcalfee** [comment]
I think your going to have to trigger another serial validation cycle on submit even if one is running.  This is the only way to guarantee valid values are submitted.  You could keep a form-level validated boolean to optimize it.

**Comment by twisty** [comment]
Hello there @jcalfee , many thanks for your feedback.

I've gone ahead with my plan to immediately call the formsy-react `setValue` method when hitting the <kbd>Enter</kbd> key (https://github.com/twisty/formsy-react-components/commit/affdf7ff576b6db523351acc9719f1dd16f6b864). The call to `setValue` triggers a new validation for the whole formsy-react form and should ensure the formsy-react `model` argument is in-sync with the UI in the various formsy-react submit methods (like `onValidSubmit`).

I hope this fixes the problem you reported. A new alpha release should forthcoming (within the next couple of days).

**Comment by jcalfee** [comment]
I can't break it by hand.. Enter and submit will always validate and submit the correct values.
