### ISSUE TITLE
[1.0.0-alpha.6] TypeError: _formsyReact.withFormsy is not a function

### ISSUE THREAD

**Issue by jcalfee** [twisty/formsy-react-components#113]
![image](https://user-images.githubusercontent.com/204121/31142164-13f78e90-a83f-11e7-980f-897b4d8275c3.png)

>+ formsy-react@1.0.0
>+ formsy-react-components@1.0.0-alpha.6

**Comment by jcalfee** [comment]
Same code works in alpha.5

**Comment by twisty** [comment]
Hmm. Not sure how that happened! Try alpha 7.

**Comment by jcalfee** [comment]
works .. thank you
