### ISSUE TITLE
Custom style for checkboxes

### ISSUE THREAD

**Issue by ngeien** [twisty/formsy-react-components#116]
Hi,
I would really appreciate if you could add a SPAN tag around or before the rendering of the valueLabel prop in Checkbox and CheckboxGroup components to better support custom styling of checkboxes. It would allow something like this:

`
input[type="checkbox"]:not(:checked) ~ span:before { content: ""; }
input[type="checkbox"]:checked ~ span { content: "✕"; }
input[type="checkbox"][disabled] ~ span { /* custom styling */ }
`

More information can be found at [Stackoverflow](https://stackoverflow.com/questions/44279398/customize-bootstrap-checkboxes).

Thanks.

**Comment by twisty** [comment]
I see what you mean. I'll consider this.

More (although Bootstrap 4) at: https://github.com/twbs/bootstrap/pull/23444

**Comment by twisty** [comment]
Closing because old and proposed example deviates from the Bootstrap 3.x examples. Future versions will support Bootstrap 4, and think the updated markup will solve this problem.
