### ISSUE TITLE
Use getValue() instead of value

### ISSUE THREAD

**Issue by jjbskir** [twisty/formsy-react-components#117]
Most of the input components are using `value`, but [formsy-react](https://github.com/christianalfoni/formsy-react/blob/master/API.md#value) says to use `getValue()`.

> You should always use the getValue() method inside your formsy form element. To pass an initial value, use the value attribute. This value will become the "pristine" value and any reset of the form will bring back this value.

Should there be an update to use this method?

**Comment by twisty** [comment]
Don't worry! In usage, the `value` you see in the individual components always comes via `getValue()`:

https://github.com/twisty/formsy-react-components/blob/1687a8541834c04fc9602faf480389298f191a4a/src/hoc/component.js#L128
