### ISSUE TITLE
React 16.1.1, Formsy 1.1:  mixins problem

### ISSUE THREAD

**Issue by StalkAlex** [twisty/formsy-react-components#119]
Here's what console says, previously everything worked fine.
![capture](https://user-images.githubusercontent.com/2943154/32940016-3b027586-cba3-11e7-914f-44ca6fd74d42.JPG)

**Comment by twisty** [comment]
What version of `formsy-react-components`?

**Comment by StalkAlex** [comment]
Last one, 0.11

**Comment by twisty** [comment]
Okay, our `0.x` releases require the `0.x` releases of `formsy-react`.

https://github.com/twisty/formsy-react-components/blob/3848d0a8d160d650fa64474f8b81cea032cfc17b/package.json#L34-L38

Support for the latest and greatest is being worked-on in our 1.0-alpha releases. I'm planning to release a beta soon that has been tested with the peer-deps that are failing for you.

**Comment by StalkAlex** [comment]
Great, thanks! Look forward to try:)
