### ISSUE TITLE
Any thoughts on custom class names?

### ISSUE THREAD

**Issue by ericdfields** [twisty/formsy-react-components#12]
Specifically [for rows](https://github.com/twisty/formsy-react-components/blob/master/src/row.js#L58-L99), I'd want to be able to arrange them on the page with arbitrary class names based on my grid, etc.

Right now we're using Bootstrap, but moving away from it is in the cards.

I can do a PR of what I think I'd do.

**Comment by aphillipo** [comment]
I need this too.

**Comment by Semigradsky** [comment]
Why not just create your own component for this?

**Comment by aphillipo** [comment]
It's not that hard to add custom classnames to a row in the current source.  Currently I'm lazy and just wrapping the few things I need to class at that level in an unneeded div.

**Comment by ericdfields** [comment]
That’s what I wound up doing. 

Initially I thought of this library as a standalone, but it seems more like a good piece of inspiration to start rolling your own components.

Happy to close this.

**Comment by twisty** [comment]
@ericdfields Thanks for the feedback... It's always been at the back of my mind that we should be able to customise various classnames. Initially I just chose the bootstrap column classnames so that it 'just worked' with the plain vanilla bootstrap CSS. I didn't fancy having to require users add any custom stylesheets.

Also, I think you're right about treating this a point of inspiration. It's possible to that there may still be useful bits you could use when creating your own component, see the mixins for instance.

**Comment by aphillipo** [comment]
I personally would leave the bootstrap classnames but often you want to ad a few extra styles to a one off component.  Would much prefer merging the styles, although extending this and writing my own might also work.  Thanks, Andy.

**Comment by twisty** [comment]
I think if we allow customising, we should allow overwriting the defaults that I arbitrarily hard coded ;-) They "work for me", but I can see it might be annoying if you wanted to used another set of bootstrap column widths, for example.  We could explain how retain the original classnames in the mythical(!) docs.

I'm thinking that row and element wrapper classes could be set at the form level, rather than individually on an component by component basis (then allow overriding in components). If you still needed to create custom components, the form-level custom classnames could possibly be accessed by using the ComponentMixin.

Probably best to go with allowing to pass a string or array of classnames to allow most flexibility (especially to allow using the unmodified bootstrap stylesheets and bootstrap column widths for a responsive layout).

**Comment by twisty** [comment]
Reopening this, as I think it we should allow customising some of the classnames.

**Comment by ericdfields** [comment]
I hadn't thought of setting the row and el classes on the form level, but I like that a lot.

I would leverage https://github.com/JedWatson/classnames to compose the classnames of multiple elements. In my experience, you can throw any combination of arrays, objects ({extraClass: this.props.useExtraClass}), and strings and get a proper class string.

**Comment by twisty** [comment]
Thanks @ericdfields for the https://github.com/JedWatson/classnames recommendation. The dedupe option looks good for (optionally) allowing removal of the default classes, while keeping it simple to add extra classes.

**Comment by erzzo** [comment]
@ericdfields I've needed this too, so I've created it here https://github.com/erzzo/formsy-react-components/commit/e832f7a15b6e2ab63909016508d0b6cdcb978884. I hope this is what you meant.
Now I use it this way
```
<Input type="text" name="name" label="name:" labelClassName="col-md-4" wrapperClassName="col-md-8"/>
```

**Comment by wkerswell** [comment]
This does look like something I would use as well. @erzzo I like your implementation. Could we merge that into the master? Wouldn't break anything and gives people a little more flexibility.

**Comment by wkerswell** [comment]
Although I have a different case where I don't want the form to have a `.row` class but would like it to have a wrapper class. So maybe setting it at a form level would be good or changing it so we can overwrite all the classes on the input.

**Comment by twisty** [comment]
Hi, I've gone ahead and added @erzzo's implementation, it should solve the problem for most people. Thank you @erzzo for that!

I think maybe allowing all classnames to be set and running them all through https://github.com/JedWatson/classnames is an inevitable next step, as it should still allow for sensible defaults, while also allowing any classname manipulation. Downsides to this are increased filesize for this component (we'd be adding another dependency), and the dedupe option may harm performance (if there are lots of components / classes).

@wkerswell I'm looking into enabling changing the wrapper class, watch this space!

**Comment by wkerswell** [comment]
I have added a custom layout type so that all the wrapper classes can be changed. I will submit a PR so you can see if it is something that would be useful or not.

**Comment by wkerswell** [comment]
Here is the PR https://github.com/twisty/formsy-react-components/pull/27 Hope it went ok got some merge conflicts from the branch being updated...

**Comment by twisty** [comment]
Thanks for that. Have just been noodling about on a similar approach, will have a look later. Cheers.

**Comment by twisty** [comment]
Hi there. In 61b5fcdbc45bf795fee38adba3c013253087fee7 i've added the ability to add or remove classes from the Row element, see the [playground example](https://github.com/twisty/formsy-react-components/blob/1c15bdffa3f1511d333eb9084d621a6a95e7715e/playground/app.js#L254-L268) for details.

(I'd come up with something quite similar to https://github.com/twisty/formsy-react-components/pull/27 -- which I think I'll close now, although I will take away the idea of adding a 'custom' layout type. The way that we implement layouts should probably be refactored anyway.)

I'd also like to add the ability to change these class name properties at the form level. This will likely be similar to the implementation for the layout property (see the [parent context mixin](https://github.com/twisty/formsy-react-components/blob/master/src/mixins/parent-context.js) and [component mixin](https://github.com/twisty/formsy-react-components/blob/master/src/mixins/component.js#L37-L40) for examples) -- although, I won't be able to begin this until the start of next week.

**Comment by wkerswell** [comment]
Awesome thanks. I cant seem to see the version 0.5.0 on npm have you updated it?

**Comment by twisty** [comment]
Just published it.

**Comment by cornerolive** [comment]
FYI:

The className you have to put in case you want to overwrite is **elementWrapperClassName** and not wrapperClassName. @erzzo 
Thank you also for making this feature!

**Comment by twisty** [comment]
@cornerolive Thanks for pointing that out. I've added [a page in the wiki](https://github.com/twisty/formsy-react-components/wiki/Class-Names) with a bit more detail.
