### ISSUE TITLE
No Negative Numbers in Input

### ISSUE THREAD

**Issue by Alonski** [twisty/formsy-react-components#120]
Hello,
How would I go about doing this?
I have for example this:
`
                    <Input
                      name="maxAmount"
                      id="maxamount-input"
                      type="number"
                      label="Maximum amount of 123"
                      value={maxAmount}
                      placeholder="10"
                      validations="greaterThan:0.1"
                      validationErrors={{
                        greaterThan: 'Minimum value must be at least ;0.1',
                      }}
                      required
                    />
`

I want this Input to not be able to go below 0 or even to not go below 0.1.
Can this be achieved?

**Comment by twisty** [comment]
Hi, this is possible by writing your own validator! 😁 

Check out `addValidationRule` in the formsy docs for an example.

* [addValidationRule in the 0.19 formsy docs](https://github.com/christianalfoni/formsy-react/blob/master/API.md#formsyaddvalidationrule) (for the 0.11 release of `formsy-react-components`).
* [addValidationRule in the 1.x formsy docs](https://github.com/formsy/formsy-react/blob/master/API.md#addvalidationrulename-rulefunc)  (for the 1.x beta release of `formsy-react-components`).

**Comment by Alonski** [comment]
We have validation but currently it only shows an error. You're saying a validator can also do what I want?

**Comment by twisty** [comment]
What you are asking should certainly be possible with a custom validation rule.

We don't ship any validators with `formsy-react-components`, they are provided by the [formsy-react](https://github.com/formsy/formsy-react) package. Our components merely display validation errors if they are present.

Perhaps raise an issue on the `formsy-react` repo or ask on Stackoverflow (with code samples), if your validation isn't working as you'd expect.

**Comment by Alonski** [comment]
Ok thanks a lot. Awesome work
