### ISSUE TITLE
Change label prop to support PropTypes.node

### ISSUE THREAD

**Issue by labkey-nicka** [twisty/formsy-react-components#121]
Hi,

We recently migrated from `0.11.0` to `1.0.0-beta.2` and are now seeing the following warning from React (`16.2.0`):

```
Warning: Failed prop type: Invalid prop `label` of type `object` supplied to `Textarea`, expected `string`.
    in Textarea (created by withFRC(Textarea))
    in withFRC(Textarea) (created by Formsy(withFRC(Textarea)))
    ...
```

It looks like this is due to a discrepancy between [ComponentCommon.propTypes.label](https://github.com/twisty/formsy-react-components/blob/master/src/components/component-common.js#L16) which is set to `PropTypes.string` and [Label.PropTypes.label](https://github.com/twisty/formsy-react-components/blob/master/src/components/label.js#L44) which is set to `PropTypes.node`.

We use the `PropTypes.node` variety (hence the warning). Since `Label` is where it is actually implemented I recommend that `ComponentCommon` be switched:

```js
ComponentCommon.propTypes = {
    //...
    label: PropTypes.oneOfType({
        PropTypes.string,
        PropTypes.node
        // and maybe PropTypes.object?
    })
}
```

Here is an example of our usage:
```ts
<Textarea label={<LabelOverlay foo={bar}/>} ... />
```

Thanks!

**Comment by twisty** [comment]
Good catch. 🎣👍

I think just `PropTypes.node` should do it (because `PropTypes.string` is encompassed in `PropTypes.node` as a "thing" that can be rendered?)

```javascript
ComponentCommon.propTypes = {
    //...
    label: PropTypes.node
}
```

I'll try and make a new release tomorrow.

**Comment by labkey-nicka** [comment]
Thank you for the fix. I think there may be one other place this needs to be adjusted which is in [ComponentHOC.propTypes.label](https://github.com/twisty/formsy-react-components/blob/master/src/hoc/component.js#L184). If you'd prefer I can open a new issue for this HOC variant.

**Comment by twisty** [comment]
Okay, noted! (Reopening, so no need to open a new issue.)
