### ISSUE TITLE
Doubt/Feature: Prevent Select setValue

### ISSUE THREAD

**Issue by xumbino** [twisty/formsy-react-components#122]
Hello,

I need to warn the user about a change he might make, and if he decides to cancel I don't want the select value to change.
However the default onChange set the value right away, and I need to wait for the user validation.

Is there a way to get around this or the default onChange?

Best Regards,
Rúben Barros

**Comment by twisty** [comment]
Hello Rúben, sorry for the delay getting back to you about this.

Did you come up with a solution to your problem? It's difficult to figure out if this is a problem that can be fixed in this component, or if it's a general form design issue.

**Comment by twisty** [comment]
Closing this one. Hope you figured it out.
