### ISSUE TITLE
Select with numerical values

### ISSUE THREAD

**Issue by SachaG** [twisty/formsy-react-components#127]
I'm getting a warning because my values are numbers, not strings:

https://github.com/twisty/formsy-react-components/blob/master/src/components/select.js#L64

```
Warning: Failed prop type: Invalid prop `options[1].value` of type `number` supplied to `SelectControl`, expected `string`.
```

Should I be converting my number to strings before passing them to the `Select`? Or should this be fixed so that selects can also handle numerical values?

**Comment by twisty** [comment]
For now, just convert the numbers to strings. The `selected` attribute is added by React, and I'm not sure how it would deal with two values like `1` (int) and `"1"` (string).

Just accepting strings makes it easier to reason about. An option might be to use `formsy-react`'s [mapping](https://github.com/christianalfoni/formsy-react/blob/master/API.md#mapping) option to manipulate the string value back to another data type on submit.

I notice `react-select` does a [string conversion](https://github.com/JedWatson/react-select/blob/649d1f4d978bc9d73956855a7ebd4c9669d11f4d/src/Select.js#L20-L23), so I may explore this avenue in the future.

```js
const stringifyValue = value =>
	typeof value === 'string'
		? value
		: (value !== null && JSON.stringify(value)) || '';
```
