### ISSUE TITLE
Does this work with bootstrap 4?

### ISSUE THREAD

**Issue by PeteW** [twisty/formsy-react-components#135]
Consider the code:
```
<Form validatePristine={true} validateBeforeSubmit={true} validateOnSubmit={false} layout='vertical'>
    <fieldset>
        <legend>Item details</legend>
        <Input name="secret" value={this.props.id} type="hidden" />
        <Input
            name="name"
            id="name"
            value=""
            label="Name"
            type="text"
            showErrors={true}
            placeholder="Enter the name of the item"
            help="Items have a name"
            changeCallback={(name: any, value: any) => this.setState({ Name: value })}
            validations="isExisty"
            validationErrors="must be nonempty"
            required={true}
        />
        <Select
            name="category"
            label="Category"
            help="Items have a category"
            changeCallback={(name: any, value: any) => this.setState({ ItemCategoryId: value })}
            options={[
                { value: '', label: 'Please Select...' },
                { value: 1, label: 'Cat1' },
                { value: 2, label: 'Cat2' },
                { value: 3, label: 'Cat3' },
            ]}
            required
        />
    </fieldset>
</Form>
```
I would expect, if these values are blank, upon loading for the forms to show errors in red.
I do see error classes being applied to the `form-group` such as `has-error` and `has-feedback`. Looking closer these seem to be bootstrap 3 concepts not 4.

looking at the playground index.html it references bootstrap 4.3.1 which convinced me this was using bootstrap 4.3.1 but tha actual playground example online is using bootstrap 3.3.7 which had me confused for some time.

What is the current state of this library? Is it compatible with bootstrap 4? is there something wrong with my code preventing it from rendering correctly?

I am using version 1.1.0

**Comment by twisty** [comment]
Sorry for the confusion.

- 1.x releases are Bootstrap 3.
- 2.x releases (currently in alpha) are Bootstrap 4.

The playground example online is from the 1.x release (so Bootstrap 3), while the source code you probably viewed was on the `master` branch (which is the 2.x release).
