### ISSUE TITLE
New package release request

### ISSUE THREAD

**Issue by mohammadsarhan** [twisty/formsy-react-components#136]
Hey Tim,

First, thanks for building this library. Its been incredibly helpful in building out validated forms with bootstrap 4. 

I see that you've updated your library to work with formsy-react-2.x.beta but you haven't yet released a package that includes those changes. Would you be able to release a new alpha version soon?

**Comment by twisty** [comment]
Hello, thanks for the nudge!

I will be releasing another build soon, ideally I'd like to wait for an updated beta of `formsy-react`, but I may be able to pin our dependencies to a GitHub URL for `formsy-react`. Although, I need to check that it will trigger a build of `formsy-react` on `npm install`.

**Comment by mohammadsarhan** [comment]
Looks like this is done. Thanks!
