### ISSUE TITLE
Build correct releases

### ISSUE THREAD

**Issue by KillerCodeMonkey** [twisty/formsy-react-components#138]
Hey there,

with v2.0.0-beta you simply run `tsc` in your build step.
This produces simple ecmascript modules that are not usable in other projects (at least in production).

Everybody has to pass your node_module through their build step/process to get things working as expected.

It would be nice if you could create working releases for all common use cases, e.g. minified, umd bundles, esm and so on.

**Comment by rkuykendall** [comment]
@KillerCodeMonkey How do the `formsy-react` releases look? I'm using rollup, np, and a few other packages to do all that automatically, and it could be easily copied.

**Comment by KillerCodeMonkey** [comment]
they are using rollup:

https://github.com/formsy/formsy-react/blob/master/package.json#L49
and they are building common and es modules:
https://github.com/formsy/formsy-react/blob/master/rollup.config.js#L30

**Comment by twisty** [comment]
@KillerCodeMonkey `umd` build added. See https://codepen.io/twisty/full/dyodZZG

**Comment by twisty** [comment]
See https://github.com/formsy/formsy-react/issues/421 for issue loading `formsy-react` in browser.

**Comment by twisty** [comment]
@KillerCodeMonkey Closing now (because fixed in this repo). Feel free to reopen if this doesn't work for you.
