### ISSUE TITLE
Editable input for Select component

### ISSUE THREAD

**Issue by sandeep-pareek** [twisty/formsy-react-components#141]
It is such a wonderful lib to use. I feel it would add another feather to the cap if Select component was editable. 
![Screenshot (54)](https://user-images.githubusercontent.com/6332549/83887094-9285d000-a765-11ea-8063-28f41146c1ed.png)

**Comment by twisty** [comment]
Hello @sandeep-pareek. Thanks for your kind words. I can see that this may be useful, but the goal is to only implement the controls that Bootstrap itself supports... so it's unlikely that components like this will be added to this package.

**Comment by sandeep-pareek** [comment]
> Hello @sandeep-pareek. Thanks for your kind words. I can see that this may be useful, but the goal is to only implement the controls that Bootstrap itself supports... so it's unlikely that components like this will be added to this package.

Thanks @twisty.
