### ISSUE TITLE
add support for 2.1.0. and higher versions of formsy-react

### ISSUE THREAD

**Issue by mesiarm** [twisty/formsy-react-components#148]
When using <Input/> component from formsy-react-components and formsy-react version 2.1.0. and higher I got warnings: 
1: Warning: React does not recognize the `attachToForm` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `attachtoform` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
2: Warning: React does not recognize the `detachFromForm` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `detachfromform` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
3: Warning: Invalid value for prop `validate` on <input> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM.

**Comment by twisty** [comment]
Fixed in https://github.com/twisty/formsy-react-components/commit/39797b802792bc743f77827684bb8e4bb068d84d
