### ISSUE TITLE
a11y

### ISSUE THREAD

**Issue by Semigradsky** [twisty/formsy-react-components#15]
How about make inputs more accessibility with `aria-invalid` and `aria-describedby`? :wheelchair: 
See https://medium.com/@roblcopeland/how-can-i-make-my-forms-a-little-more-accessible-1726d63210f2
It would be cool

**Comment by twisty** [comment]
Yes, should really do this.

The [Bootstrap docs for forms](http://getbootstrap.com/css/#forms-control-validation) also describe what's needed pretty well.

**Comment by twisty** [comment]
Also should see this: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/forms/Basic_form_hints

**Comment by twisty** [comment]
The playground example seems to pass all tests in the [Chrome accessability audit developer tool](https://chrome.google.com/webstore/detail/accessibility-developer-t/fpkknkljclfencbdbgkenhalefipecmb).

(See list of [Audit rules](https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules).)

**Comment by twisty** [comment]
(A year and a half goes by... cleaning up old issues!)

The playground example passes the lighthouse accessibility audit. If there are specific accessibility concerns, please open separate issues.
