### ISSUE TITLE
FRC component for react-bootstrap-datetimepicker

### ISSUE THREAD

**Issue by joshgeller** [twisty/formsy-react-components#17]
Thanks for the excellent library! Do you have any interest in adding a component to wrap the [react-bootstrap-datetimepicker](https://github.com/quri/react-bootstrap-datetimepicker) component? input[type=date] isn't well-supported yet, so I could work on a pull request if you are interested. I understand if you do not want to add any dependencies. Thanks!

**Comment by joshgeller** [comment]
After spending some more time on this, the two don't play as nicely as I would like. I'd rather keep your library clean :)

**Comment by twisty** [comment]
Hi @joshgeller, thanks for reporting back. Flipping it around, it may be possible to add a dependency to this library and then use certain parts of it in your wrapper (perhaps the `<Row />` component, and the component mixins). Although... it wasn't really built with this in mind, but it gives me something else to consider moving forward!

**Comment by SachaG** [comment]
I'm also looking for a datetimepicker component to use with Formsy. Has there been any progress on this front since last year? Or any suggestions on the best way to do the integration myself?
