### ISSUE TITLE
ES6 syntax, there is a way to use formsy-react-components as not mixin?

### ISSUE THREAD

**Issue by eriknyk** [twisty/formsy-react-components#23]
Hi, I've a application using ES6 classes, and I wish to know 
if there is a way to use formsy-react-components not as mixin.

Best Regards

**Comment by Semigradsky** [comment]
What do you mean? Where do you see mixin in the example (https://github.com/twisty/formsy-react-components/blob/gh-pages/playground/app.js)?

**Comment by twisty** [comment]
Hi, you can require the components and just use them as they are, it's not necessary to include any mixin.

However, if you want to use the `parent-context` mixin, or create a new component using the `component-mixin`, maybe have a look at https://github.com/brigand/react-mixin (although I haven't tried this).
