### ISSUE TITLE
IE8 support. 

### ISSUE THREAD

**Issue by wkerswell** [twisty/formsy-react-components#25]
Will / Does this library support IE8? The current site that I am working on has a large IE8 audience and unfortunately cannot be ignored :disappointed:

**Comment by twisty** [comment]
Yes, it should be okay in IE8 (although I'll add a disclaimer here that I haven't tested this extensively in that browser).

The markup generated should pretty much conform to that in Bootstrap 3 (which supports IE8). See [Bootstrap browser support](http://getbootstrap.com/getting-started/#support).

Also, you'll need the polyfills listed on the [React browser support](https://facebook.github.io/react/docs/working-with-the-browser.html#browser-support-and-polyfills) page.

**Comment by wkerswell** [comment]
Thanks for the reply. Just checked out the exampl, added the shims and shams, it seems to work. 
Will start using this. :)

**Comment by twisty** [comment]
Great, (I should probably add those shims etc. to the example). Good luck with your project.

**Comment by wkerswell** [comment]
I have added them in and PR it in if you like?

**Comment by twisty** [comment]
That would be great, cheers.
