### ISSUE TITLE
Addon with a element throws Error

### ISSUE THREAD

**Issue by erzzo** [twisty/formsy-react-components#42]
When I set a addon with an element
```javascript
addonBefore = { <i name="test" className='ion-person' /> }
```
It throws `Uncaught TypeError: Converting circular structure to JSON`, when I doesn't set a ID
I found that error is on this line, by hashing the addon prop
https://github.com/twisty/formsy-react-components/blob/master/src/mixins/component.js#L119

But I don't have a "clean" solution for this now.

**Comment by twisty** [comment]
Fixed, see #33.
