### ISSUE TITLE
Support for RequireJs

### ISSUE THREAD

**Issue by nilocoelhojunior** [twisty/formsy-react-components#48]
[Execute](http://requirejs.org/docs/commonjs.html#autoconversion):

```
node r.js -convert path/to/commonjs/modules/ path/to/output
```

**Comment by twisty** [comment]
I'm planning to switch from browserify to webpack in the future, I'll probably add support for RequireJs via webpack's [umd](https://github.com/umdjs/umd) option at this time.

**Comment by twisty** [comment]
If anyone else would like to see this then leave a comment or reaction. I'll leave this open a little while longer, but not sure I want to introduce / support it without more demand.

**Comment by twisty** [comment]
Closing this now. Perhaps you can run this conversion as part of your project build script. Thanks, Tim.
