### ISSUE TITLE
Not bootstrap 4 ready

### ISSUE THREAD

**Issue by afgarcia86** [twisty/formsy-react-components#51]
I only bring this up as an issue because I am personally starting to use the alpha. I started using this package a week ago and it has been a life saver. I have been updating some of the components to use the new classes. If you are cool with it I will fork and create a pull request when I think its ready. I am guessing it would need to live in a separate branch unless we added some type of switch that tells the package what components to use. 

Anyway thanks for this either way!

**Comment by twisty** [comment]
Glad you've been finding this package handy!

Go ahead and fork! I'd be interested to see what's involved. You're right, I ought to create a branch for Bootstrap 4.

I guess you've seen the [Bootstrap 4 migration guide for forms](http://v4-alpha.getbootstrap.com/migration/#forms)?

I'm not sure about what to support once Bootstrap 4 comes out -- my current thinking is that once Bootstrap 4 is released we'll put the Bootstrap 3 code into maintenance mode and make a major release supporting Bootstrap 4. From then on new features will be Bootstrap 4 only. I'm thinking It would be best to avoid flags to switch rendering between Bootstrap 3 and 4.

The older version will obviously still work with Bootstrap 3 and may get some patch updates, but I'm not really keen on supporting 2 versions of Bootstrap simultaneously.

**Comment by afgarcia86** [comment]
Hello again, I finally got around to putting this together. (https://github.com/afgarcia86/formsy-react-components). I also updated the playground so that it would be easier to test.

Notes:
- I actually made the label optional, basically I wanted the elementOnly however I wanted it wrapped in the "form-group" which is actually required for the validation classes I believe
- I removed the icon from input since its now added with CSS, however I also removed it from the file input since I don't think it really added much there.

**Comment by twisty** [comment]
Hi @afgarcia86, looks good. I've created a new branch for Bootstrap 4 development (`bootstrap-4-dev`). If you like and at your convenience, you can create a PR and I'll merge it in.

Your notes are noted! I'm thinking of dropping the `elementOnly` layout, so think just not rendering the label if it isn't provided is okay. Nuking the icon is fine.

**Comment by fabdarice** [comment]
Hi @twisty @afgarcia86,

I've been trying to use the branch because I'm using bootstrap v4. 
After installing through 
` yarn add https://github.com/twisty/formsy-react-components.git#bootstrap-4-dev`

I see the following error : 
`Module not found: Error: Can't resolve 'formsy-react-components'`
`Field 'browser' doesn't contain a valid alias configuration`

I'm using : 
react@15.6.2
formsy-react@0.19.5
formsy-react-components@0.9.0

Please, advise, thanks !

**Comment by kingleuther** [comment]
FF on this. How are we going to use the formsy for bootstrap 4? thanks!
