### ISSUE TITLE
When a label is not provided but field is required, a lone * is displayed

### ISSUE THREAD

**Issue by keul** [twisty/formsy-react-components#61]
Reproduced with RadioGroup usage but probably hit also other fields.

If a label is not provided but you want the field required, you'll get a layout like this:

![schermata 2016-03-31 alle 11 31 20](https://cloud.githubusercontent.com/assets/284924/14171613/2381893c-f734-11e5-87e3-ac365bcf5b30.png)

Probably the required marker must not be displayed in this case (or maybe a new attribute for not displaying it can be useful?)

**Comment by twisty** [comment]
Hi, I can see that this looks a bit strange. By default, the labels are text-aligned right, so the asterisk would normally sit closer to the form controls. (It looks like you have aligned labels to the left, which has created a bigger gap between the 'required' asterisk symbol and the form controls.)

I think this could be fixed it I make it easier to style the 'required' asterisk via css (so it could be hidden, for example).

Something like this: https://www.w3.org/TR/WCAG20-TECHS/ARIA2.html#ARIA2-ex3

**Comment by keul** [comment]
Hi @twisty, seems fair to me. Hiding by CSS can be a good way.

**Comment by twisty** [comment]
Add css in latest release:

    <span class="required-symbol"> *</span>
