### ISSUE TITLE
React v15

### ISSUE THREAD

**Issue by copas2** [twisty/formsy-react-components#63]
Could you please move on to the newer release of React (v15)? In the moment no breaking error can be experienced when using the components in v15 environment.
The only problem right now is the package.json which requires v0.14 in its dependencies section. Moving it to devDependencies, npm-install won't pull React v0.14 into its modules tree and therefore it won't result in a conflict caused by the two React versions.

**Comment by twisty** [comment]
Hi @copas2,

Thanks for the heads-up, I'll look into it.

**Comment by franklinkim** [comment]
+1

maybe even mark `react` as `peerDependencies` like in `formsy-react`'s `package.json`!? (might also apply to the others)

```json
...
  "dependencies": {
    "formsy-react": "^0.17.0",
    "classnames": "^2.1.3"
  },
  "peerDependencies": {
    "react": "^0.14.0"
  },
...
```

**Comment by pacjin79** [comment]
Just Fyi, I ran into a invalid ref error after upgrading react from 0.14.7 to 15.0.1.  Seems this error only happens with pages containing formsy-react and formsy-react-componenents components.  I looked into this the recommended gist https://gist.github.com/jimfb/4faa6cbfb1ef476bd105  I'm not doing anything crazy with the refs and definitely do not have multiple copies of react running.  My only guess at this point is there's a breaking change either in formsy or formsy-react-components.   Switched back to 0.14.7 and all forms are working again.   Please let me know if you've ran into anything similar or any recommendations on how to proceed would be great.   Really appreciate all the effort you've put into this project, it has become an mission critical piece of my project.  thanks a lot!.

**Comment by twisty** [comment]
Hi @pacjin79, I'm pleased that you're finding this project so useful. Not sure what to suggest at the moment, I'll be making a new release this weekend with `react` moved to `devDependencies`, as suggested by @copas2. Maybe wait for that and try again?

I've just rebuilt the playground example using `react@15.0.1` and the github master version of `formsy-react-components` -- it built okay using `browserify` and seems to be fine.

@franklinkim I've gone ahead and added a peerDependencies hint for `react` v0.14 or v15. (I think `npm` version 3 no longer tries to install peer dependencies, it just warns if they're not satisfied).

**Comment by pacjin79** [comment]
Ok sounds good thanks again!

**Comment by franklinkim** [comment]
thanks!

**Comment by twisty** [comment]
Just released v0.7.1 to enable installing React v15.

**Comment by pacjin79** [comment]
awesome, trying it now.  Thanks a lot @twisty

**Comment by pacjin79** [comment]
@twisty I just realized I never reported my findings.  upgraded to react 15.0.1,  formsy-react-component 0.7.1, and formsy-react 0.18.0.  So far everything is working perfectly.  Thanks a lot for fixing this
