### ISSUE TITLE
What to do about formsy-react being abandonware?

### ISSUE THREAD

**Issue by twisty** [twisty/formsy-react-components#64]
It seems [formsy-react](https://github.com/christianalfoni/formsy-react) has been abandoned by it's owner.

At the moment it still works, but there are plenty of issues with fixes submitted by the community that can't be released without the owner's participation.

See:
- [Contributors need NPM publish access](https://github.com/christianalfoni/formsy-react/issues/290)
- [Further development](https://github.com/christianalfoni/formsy-react/issues/301)
- [Is it logical to still use formsy-react?](https://github.com/christianalfoni/formsy-react/issues/327)

**Comment by mikeerickson** [comment]
@twisty well it seems like a good time to fork and extend / update. Maybe I will do that over weekend. I will try and reach owner first and see what (if any) their intentions are.  Surely been quite some time

**Comment by twisty** [comment]
New release today. Things look like they're moving again.

**Comment by barrylavides** [comment]
There was a new release 3 days ago
https://github.com/christianalfoni/formsy-react/releases/tag/v0.18.0

**Comment by twisty** [comment]
[It is happening again](https://www.youtube.com/watch?v=pWa0dZMHYeE). Reopening.

* https://github.com/christianalfoni/formsy-react/issues/475
* https://github.com/christianalfoni/formsy-react/issues/481#issuecomment-334976398

**Comment by aliogaili** [comment]
Thanks twist for reopening this!

What do you think about aligning with [formsy-react-2](https://github.com/maccuaa/formsy-react-2)? It's unfortunate because the original library doesn't really need much work to get up to date..

**Comment by twisty** [comment]
Happy to close this...

https://github.com/formsy/formsy-react/issues/1
