### ISSUE TITLE
Row fakeLabel uses <strong>

### ISSUE THREAD

**Issue by jwentz-boc** [twisty/formsy-react-components#69]
https://github.com/twisty/formsy-react-components/blob/master/src/row.js#L76

Why? Ordinary labels, say for Input, do not.

Result is CheckboxGroup with rowLabel is bold, other form labels are not.

(Thanks for the project BTW, very useful.)

**Comment by twisty** [comment]
Labels in Bootstrap 3 are bold by default. `fakeLabel` is given a `strong` tag so it looks the same as an plain old Bootstrap 3 label. It's in a `strong` tag so we don't require the user to add any custom CSS to get a default Bootstrap 'look'.

In Bootstrap 4 (currently alpha-2) I believe that labels are not bold. Bootstrap 4 compatibility isn't supported at the moment.

**Comment by jwentz-boc** [comment]
Thanks for the reply; guess my theme has non-bold labels, leading to the discrepancy.
