### ISSUE TITLE
Input changing from uncontrolled input to controlled during component lifetime

### ISSUE THREAD

**Issue by MilosRasic** [twisty/formsy-react-components#72]
After upgrade to React v15, getting the following warning:

> warning.js?0260:44 Warning: Input is changing an uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components

This is happening only when Input is used without value prop (no initial value). I believe this could be fixed if initial value is assumed to be undefined or an empty string when none is provided (React v15 will also emit a warning if null is used).

**Comment by twisty** [comment]
Hello there, this has come up before (see #66). The answer is to pass a suitable initial value to the component (like an empty string for 'texty' types of inputs).
