### ISSUE TITLE
Using ref with callbacks vs strings

### ISSUE THREAD

**Issue by SachaG** [twisty/formsy-react-components#76]
Right now this codebase uses the `ref="string"` pattern a lot:

https://github.com/twisty/formsy-react-components/search?utf8=✓&q=ref

But the React docs mention this approach will be deprecated in favor of callbacks:

https://facebook.github.io/react/docs/more-about-refs.html

Also, for some weird reason string refs have been causing errors in certain situations, while callback refs don't. Would you consider a PR to replace the strings by callbacks?

**Comment by twisty** [comment]
Yes, go ahead!
