### ISSUE TITLE
Linux opera is unhappy about playground/bundle.js

### ISSUE THREAD

**Issue by tobez** [twisty/formsy-react-components#8]
It does not like multiple definitions of property `value` in this code:

    React.createElement(Checkbox, React.__spread({}, 
                            sharedProps, 
                            {name: "checkbox1", 
                            value: "Foo", 
                            label: "Check me out", 
                            rowLabel: "Checkbox (single)", 
                            value: true})
                        ),

**Comment by twisty** [comment]
Hi @tobez, thanks for letting me know about this one. I can't test this in Opera at the moment. But this particular problem should now be fixed.

**Comment by tobez** [comment]
I can confirm that the fix worked and that playground is operational in Opera now.  Thanks!
