### ISSUE TITLE
Add error class and show error message onBlur.

### ISSUE THREAD

**Issue by hevar** [twisty/formsy-react-components#81]
Hi,

How can I change to show error classes and error messages onBlur instead of onChange?

Thanks in advance!

**Comment by twisty** [comment]
Hi @hevar -- it isn't possible to do that at the moment.

I'm looking into adding this into a future release, probably with the option to debounce onChange.

https://github.com/nkbt/react-debounce-input

**Comment by twisty** [comment]
For future refernece: https://docs.angularjs.org/api/ng/directive/ngModelOptions

> `updateOn`: string specifying which event should the input be bound to. You can set several events using an space delimited list. There is a special event called default that matches the default events belonging of the control.
> `debounce`: integer value which contains the debounce model update value in milliseconds. A value of `0` triggers an immediate update. If an object is supplied instead, you can specify a custom value for each event. For example: `ng-model-options="{ updateOn: 'default blur', debounce: { 'default': 500, 'blur': 0 } }"`

**Comment by hevar** [comment]
Well I've accomplished to show error message onBlur (a bit hacky, but still). So all that is left is to do something similar in the row.js.

**Show error onBlur (input.js) :** 

       changeValueOnBlur: function changeValueOnBlur(event) {
           this.props.onBlur(this.props.name, this.getValue());
            if (this.state.isValid) {
                this.setState({
                    inputIsValid: true
                })
            } else {
                this.setState({
                    inputIsValid: false
                })
            }
        },


Can i somehow similar to above do

    cssClasses.row.push('has-danger');

in the row.js when the input field is invalid?

**Comment by hevar** [comment]
Great work btw, and I look forward for the new features! 💃

**Comment by twisty** [comment]
Options for updating `onChange` and `onBlur` are available on the master branch. v1.0 will be released from this branch in due course, but alphas are available now with this functionality.
