### ISSUE TITLE
Default value on input?

### ISSUE THREAD

**Issue by hchoriq** [twisty/formsy-react-components#88]
Is there a reason Input component does not allow setting a defaultValue for text fields?

**Comment by twisty** [comment]
Hi @hchoriq, the ```defaultValue``` prop is for [uncontrolled components](https://facebook.github.io/react/docs/uncontrolled-components.html), all the form controls in this library are designed as [controlled components](https://facebook.github.io/react/docs/forms.html).

You can pass an initial value to the control by using the ```value``` prop (see [Formsy.Mixin: value prop](https://github.com/christianalfoni/formsy-react/blob/master/API.md#value))

**Comment by hchoriq** [comment]
Thanks! I figured out my problem. It had nothing to do with defaultValue; I kept getting the 'uncontrolled component turning into a controlled component' warning because value was set to a prop which was null at the time. I fixed it by setting value={this.props.name || ''}
