### ISSUE TITLE
Can't get select value in onChange function

### ISSUE THREAD

**Issue by virtser** [twisty/formsy-react-components#90]
I was expecting to get the same event object as in [native select](https://facebook.github.io/react/docs/forms.html) and access the selected value in `` event.target.value``, but instead I get in event only the select name.

 ```
onChange(event) {
  let fooValue = event.target.value; // Got event name "foo" in event variable instead of "2".
}

render() {
  return ( 
    <FRC.Select name="foo" options="[{value: '1', label: 'A'}, {value: '2', label: 'B'}]" onChange={this.onChange} />
  );
```

**Comment by twisty** [comment]
The value is passed as the second argument; so use: `onChange(name, value)`.

Hope that helps.

**Comment by virtser** [comment]
Oh, thanks a lot @twisty that was it! 👍
