### ISSUE TITLE
React warnings

### ISSUE THREAD

**Issue by carlos-sarmiento** [twisty/formsy-react-components#94]
React is showing the following warnings when using formsy-react-components. Doesn't seem to affect behavior.

When rendering the form:
- Unknown prop `layout` on `<form>` tag

When editing an Input field
- Input is changing an uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component.

**Comment by twisty** [comment]
Hi @carlos-sarmiento,

Unknown prop fixed in [8342aa418b9eea790a541324fc8c2f5bfde47c92], version 0.10.1 will be released shortly with this included.

For the `<Input />` field issue, make sure to pass a value (an empty string will do), and that should fix it (see #66).
