### ISSUE TITLE
Checkbox label doesn't show where is should be

### ISSUE THREAD

**Issue by flavio-elder** [twisty/formsy-react-components#98]
Hello,

i'm using 0.10.1 of formsy-react-components and the rendering of a single checkbox isn't right. If i add a 'label' it acts like a 'valueLabel' and doesn't work.

Anyone else having that issue?

code example:

```javascript
<Checkbox
    name='blabla'
    value={blabla}
    label='My label acting as a valueLabel =('
/>
```

in the generated DOM, the element with a class `control-label` doesn't have the expected label (it's empty)

**Comment by twisty** [comment]
Hi @flavio-elder,

Sorry for this confusion! The `master` branch is the source for a future 1.0 release; there is a `release-0.x` branch that current npm releases are cut from.

I think you've discovered one of the only API changes between the 0.x release and the proposed 1.x version. See: [migrating to 1.0.0](https://github.com/twisty/formsy-react-components/blob/master/docs/migrating-to-1.0.0.md#checkbox-component) for more on this proposed change.

For now, use `rowLabel` for the row label, and `label` for the value label.

I need to add some info in the READMEs in each branch to explain what's going on.

All the best,

Tim.
